Toggle for enabling/disabling the map on result. Also fixed map location error when crossing antimeridian
frdr-dfdr/frdr_discovery_v2_frontend pull request #19
Opened 2022-09-09 07:34 UTC by pdante-ubc

Toggle switch enables or disables the map for location filtering of results. Also created a fix for when the map tries to load when crossing the antimeridian

2022-09-16 12:29 UTC, pdante-ubc commented
Ok, so there are a number of files that have been changed, but really I think only home.js, geosearch.js, results.js and map.js deal with the map disabling and the anti-meridian issue.

2022-09-23 20:43 UTC, adammckenzie commented
Hi Paul, while playing around with the feature I think I might have discovered a bug on dev2. Sorry dev1 is currently not responding so I can't deploy and test there. 

Steps to reproduce:
1) Home page do an empty search
2) Enable map search
3) Type in Mountain and click on "Search" button

Result: Enable map search is disabled.

2022-09-23 20:43 UTC, adammckenzie commented
I think we should have a bigger margin between the left hand side and the enable slider to match the spacing on the rest of the page.

2022-09-23 20:44 UTC, adammckenzie requested changes

2022-09-23 20:44 UTC, adammckenzie commented on app/views/catalog/_document_split.html.erb
> +    <ul class="no_bullets">
Just curious what problem is solved by the unordered list instead of two divs?

2022-09-23 20:44 UTC, adammckenzie commented on vendor/assets/javascript/leaflet.js
> +!function(t,i){"object"==typeof exports&&"undefined"!=typeof module?i(exports):"function"==typeof define&&define.amd?define(["exports"],i):i(t.L={})}(this,function(t){"use strict";function h(t){for(v
Hi Paul, I think this is not a good idea. If we change a library by editing it in this way to change the name of the png file then we will forever have to patch the library every time we upgrade a new version with the different png file. The png file name can be set either in the css file for leaflet or when defining the map in javascript by setting the icon options. Has anything else been changed in this file in our repo from the base version of leaflet?

2022-10-03 07:31 UTC, pdante-ubc commented on vendor/assets/javascript/leaflet.js
> +!function(t,i){"object"==typeof exports&&"undefined"!=typeof module?i(exports):"function"==typeof define&&define.amd?define(["exports"],i):i(t.L={})}(this,function(t){"use strict";function h(t){for(v
I 100% agree. These changes were only made when I was trying to test changing the marker color, and they should not have stayed.

2022-10-06 19:22 UTC, pdante-ubc commented on app/assets/javascripts/geoblacklight/modules/results.js
> +        label.textContent = "Limit by map area"
Fixed

2022-10-06 19:22 UTC, pdante-ubc commented on app/views/catalog/_document_split.html.erb
> +    <ul class="no_bullets">
Isn't one, fixed

2022-10-06 19:57 UTC, merged